
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./php/src:/var/www/html:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    build:
      context: .
      dockerfile: php.dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes:
        - ./php/src:/var/www/html:delegated