version: "3.3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/nginx.dockerfile
      args:
        ENABLED_MODULES: ndk lua
    restart: always
    ports:
      - 80:80
    volumes:
      - ./php/src:/var/www/html:delegated

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./php/php.dockerfile
    restart: always
    ports:
      - 9000:9000
    volumes:
        - ./php/src:/var/www/html:delegated

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml