FROM postgres:latest

# RUN echo "host replication all 0.0.0.0/0 md5" > /usr/share/postgresql/postgresql.conf

# COPY ./primary-entrypoint.sh /docker-entrypoint-initdb.d/

# COPY ./pg_hba.conf /pg_hba.conf
# COPY ./postgresql.conf /postgresql.conf
