version: '3.8'

services:
  primary:
    build:
      context: .
      dockerfile: Dockerfile.primary
    environment:
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main__password
      POSTGRES_DB: primary_db
    # volumes:
      # - ./data/p:/var/lib/postgresql/data
      # - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      
    networks:
      - postgres_net

  replica:
    build:
      context: .
      dockerfile: Dockerfile.replica
    environment:
      POSTGRES_USER: replica_user
      POSTGRES_PASSWORD: replica_password
      POSTGRES_DB: replica_db
      POSTGRES_PRIMARY_HOST: primary
      POSTGRES_PRIMARY_PORT: 5432
      POSTGRES_PRIMARY_USER: primary_user
      POSTGRES_PRIMARY_PASSWORD: primary_password
    depends_on:
      - primary
    # volumes:
    #   - ./data/r:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  primary_data:
  replica_data:

networks:
  postgres_net:
